name: Generate extension list

on:
  schedule:
    - cron: '11 11 * * *'
  workflow_dispatch: ~

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE: extensions.json

    steps:
      - name: Checkout source code # zizmor: ignore[artipacked] Credentials are needed later
        uses: actions/checkout@v6

      - name: Build JSON file
        run: php ./generate.php

      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Get changes
        id: diff
        run: |
          DIFF=$(git diff --numstat -- $FILE | wc -l)
          echo "DIFF=$DIFF" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: |
          git add $FILE
          git commit -m 'Update extension list'
          git push origin $GITHUB_REF
        if: steps.diff.outputs.DIFF != 0
